/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.esystem;

import javax.swing.table.DefaultTableModel;



/**
 *
 * @author amalda
 */
public class SubjectGUI extends javax.swing.JFrame {
    
    public static int selectedSubjectId = -1;
    public static int selectedStudentId = -1;
    public static int selectedTeacherId = -1;
    public static int selectedAssignSubjectId = -1;
    public static int selectedEnrollSubjectId = -1;

    /**
     * Creates new form SubjectGUI
     */
    public SubjectGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjCode = new javax.swing.JTextField();
        Save = new javax.swing.JToggleButton();
        Update = new javax.swing.JToggleButton();
        Delete = new javax.swing.JToggleButton();
        subjId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subjDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        subjUnits = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        subjSched = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        classTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        subjCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjCodeActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        subjId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjIdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Code:");

        jLabel3.setText("Description:");

        subjDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjDescActionPerformed(evt);
            }
        });

        jLabel4.setText("Units:");

        subjUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjUnitsActionPerformed(evt);
            }
        });

        jLabel5.setText("Schedule:");

        subjSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjSchedActionPerformed(evt);
            }
        });

        subjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Code", "Units", "Schedule", "Description"
            }
        ));
        subjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subjTable);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 0, 255));
        jLabel7.setText("Subjects Form");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Class List");

        classTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "StudID", "Name", "Address", "Course", "Gender", "Year"
            }
        ));
        classTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(classTable);

        jMenu1.setText("Form");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Students");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Teachers");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(Save)
                                .addGap(60, 60, 60)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(Update))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(subjDesc))
                                    .addComponent(subjSched)
                                    .addComponent(subjId)
                                    .addComponent(subjCode)
                                    .addComponent(subjUnits, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(subjCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(subjUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(subjSched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(subjDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Save)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Delete)
                                .addComponent(Update)))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subjCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjCodeActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        Subject sub = new Subject();
        sub.SaveRecord(Integer.valueOf(subjId.getText()), subjCode.getText(), subjSched.getText(), Integer.valueOf(subjUnits.getText()), subjDesc.getText());
        showRecords();
    }//GEN-LAST:event_SaveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        showRecords();
        Subject sub = new Subject();
        sub.UpdateRecord(Integer.valueOf(subjId.getText()), subjCode.getText(), subjSched.getText(), Integer.valueOf(subjUnits.getText()), subjDesc.getText());
        showRecords();
    }//GEN-LAST:event_UpdateActionPerformed

    private void subjIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjIdActionPerformed

    private void subjDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjDescActionPerformed

    private void subjUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjUnitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjUnitsActionPerformed

    private void subjSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjSchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjSchedActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        StudentGUI student = new StudentGUI();
        student.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        TeacherGUI teacher = new TeacherGUI();
        teacher.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void subjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjTableMouseClicked
        int row = subjTable.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            subjId.setText(subjTable.getValueAt(row,0).toString());
            subjCode.setText(subjTable.getValueAt(row,1).toString());
            subjSched.setText(subjTable.getValueAt(row,2).toString());
            subjUnits.setText(subjTable.getValueAt(row,3).toString());
            subjDesc.setText(subjTable.getValueAt(row,4).toString());
        }
        
        selectedSubjectId = Integer.parseInt(subjTable.getValueAt(row,0).toString());
        showEnrollRec();
    }//GEN-LAST:event_subjTableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showRecords();
        Subject load = new Subject();
        load.LoadRecords();
    }//GEN-LAST:event_formWindowOpened

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        showRecords();
        Subject sub = new Subject();
        sub.DeleteRecord(Integer.valueOf(subjCode.getText()));
        showRecords();
    }//GEN-LAST:event_DeleteActionPerformed

    private void classTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_classTableMouseClicked

    public void showRecords() {
    DefaultTableModel tblmodel = (DefaultTableModel) subjTable.getModel();
    tblmodel.setRowCount(0);
    ESystem show = new ESystem();
    show.DBConnect();
    try {
        String query = "SELECT * FROM Subjects;";
        show.rs = show.st.executeQuery(query);
        while (show.rs.next()) {
            String id = show.rs.getString("subjid");
            String code = show.rs.getString("subjcode");
            String sched = show.rs.getString("subjsched");
            String units = show.rs.getString("subjunits");
            String desc = show.rs.getString("subjdesc");

            String[] item = {id, code, sched, units, desc};
            tblmodel.addRow(item);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    public void showEnrollRec() {
        DefaultTableModel model = (DefaultTableModel) classTable.getModel();
        model.setRowCount(0); 
        
        if (selectedSubjectId == -1) {
            return;
        }
        
        ESystem show = new ESystem();
        show.DBConnect();
        try {
            String query = "SELECT * FROM Students JOIN Enroll ON Students.studid = Enroll.studid WHERE Enroll.subjid = " + selectedSubjectId;
            
            show.rs = show.st.executeQuery(query);
            
            while (show.rs.next()) {
                String studentId = show.rs.getString("studid");
                String name = show.rs.getString("studname");
                String address = show.rs.getString("studadd");
                String contact = show.rs.getString("studcontact");
                String gender = show.rs.getString("studgender");
                String yearLevel = show.rs.getString("studyrlvl");
                
                model.addRow(new String[]{studentId, name, address, contact, gender, yearLevel});
            }
            
        } catch (Exception ex) { System.out.println(ex); }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Delete;
    private javax.swing.JToggleButton Save;
    private javax.swing.JToggleButton Update;
    private javax.swing.JTable classTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField subjCode;
    private javax.swing.JTextField subjDesc;
    private javax.swing.JTextField subjId;
    private javax.swing.JTextField subjSched;
    private javax.swing.JTable subjTable;
    private javax.swing.JTextField subjUnits;
    // End of variables declaration//GEN-END:variables
}
